### ISSUE TITLE
exclude_polygons: how does it work?

### ISSUE THREAD

**Issue by phcantis** [chris31415926535/valhallr#5]
Hi! thank you so much for creating an interface between Valhalla and R! I am really excited to dig into it. I am interested in the applications offered by Valhalla to exclude routes based on a GIS input, such as [here](https://github.com/valhalla/valhalla/issues/1740).

I went through the documentation of the library ([dated March 9th](https://cran.r-project.org/web/packages/valhallr/valhallr.pdf)) and it did not seem to me like the interface has this functionality included. However, I checked the code in the Valhalla.R file and saw that some functions now have `exclude_polygons=NA` as an argument. Could this mean that this functionality has been added and the documentation is outdated? Would be happy to test this functionality if so - and potentially support readme / documentation dev if you are too stretched.

**Comment by chris31415926535** [comment]
Hi, thanks for your interest!

The `exclude_polygons` argument is available in the latest dev version of the package on GitHub, whereas the documentation you linked to is for the stable CRAN release. So if you install the dev version with `devtools::install_github("chris31415926535/valhallr")` you'll have the most recent code with that functionality enabled.

You're right I should update the docs, and in general I need to do some updates with this package to get these new features on CRAN! In the meantime though [you can see a full worked example of excluding polygons here.](https://github.com/chris31415926535/valhallr/issues/4) 

I added this feature pretty recently and did some basic testing, so if you use it it'd be great to get your feedback.

**Comment by phcantis** [comment]
Thanks for your fast answer! I have a learning curve to face - I have never deployed Valhalla in my machine and it seems like the next thing to unlock. I will keep you posted as I carve the time to run this. Meanwhile I will star the repo so I stay updated with changes.

Cheers!
